Elementizes plastic flap hitbox behavior into the Render over, Keep hitbox element! Applies to directional windows
wall-nerds/wallening pull request #115
Opened 2022-10-01 20:27 UTC by tralezab

## About The Pull Request

Plastic flaps render over people, but you're still able to hit the person crawling under. This is exactly what directional windows need to act properly, so I've elementized the behavior and applied to both!

## Why It's Good For The Game

Fixes #110 

## Changelog

:cl:
fix: Directional windows now properly render over you
/:cl:

2022-10-01 20:31 UTC, MrMelbert requested changes

2022-10-01 20:31 UTC, MrMelbert commented on code/datums/elements/render_over_keep_hitbox.dm
> +	. = ..()
```suggestion
	return ..()
```

2022-10-01 20:31 UTC, MrMelbert commented on code/datums/elements/render_over_keep_hitbox.dm
> +	if(!istype(target, /obj/structure))
```suggestion
	if(!isstructure(target))
```

2022-10-01 20:31 UTC, MrMelbert commented on code/datums/elements/render_over_keep_hitbox.dm
> +	if(same_z_layer)
```suggestion
/datum/element/render_over_keep_hitbox/proc/on_changed_z_level(obj/structure/target, turf/old_turf, turf/new_turf, same_z_layer)
	SIGNAL_HANDLER
	
	if(same_z_layer)
```

2022-10-01 20:31 UTC, MrMelbert commented on code/datums/elements/render_over_keep_hitbox.dm
> +	return
```suggestion
```

2022-10-01 21:11 UTC, LemonInTheDark requested changes

2022-10-01 21:11 UTC, LemonInTheDark commented on code/datums/elements/ranged_attacks.dm
> +		return ELEMENT_INCOMPATIBLE
not here, I don't want misc changes out of risk of more merge conflicts

2022-10-01 21:11 UTC, LemonInTheDark commented on code/datums/elements/render_over_keep_hitbox.dm
> +	)
do we need to use vis_contents for this to work?
~~also how does this work~~

2022-10-01 21:15 UTC, LemonInTheDark commented
> NOTE: Plastic flap code does pic related, and so this element brings that visual error with it. But it's still worth! ![image]

This is an issue of sidemap.
Basically since everything (the window and the mob) are on the same plane, we decide rendering order based off (oversimplifying)
"position (x + pixel_x, bounded to blocks of 32x32)"
failing that, layer

This means you can in theory construct a window that renders below when we want it to, and above when we want it to, which is what we want here.
Getting it to be click transparent is another issue, not sure how you go about that.

2022-10-14 19:02 UTC, tralezab commented
mkay, i'm back

2022-10-25 08:48 UTC, merged